/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project1;

import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Mertcan Karabaş
 */
public class SoloNoble extends javax.swing.JFrame {

    /**
     * Creates new form SoloNoble
     */
    
    public SoloNoble() {        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_arkaEkran = new javax.swing.JPanel();
        lbl_ayrim = new javax.swing.JLabel();
        pnl_log = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnl_oyunEkrani = new javax.swing.JPanel();
        pnl_ustPanel = new javax.swing.JPanel();
        cmbx_butonSayisi = new javax.swing.JComboBox<>();
        btn_basla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_arkaEkran.setBackground(new java.awt.Color(51, 51, 51));
        pnl_arkaEkran.setMaximumSize(new java.awt.Dimension(800, 600));
        pnl_arkaEkran.setMinimumSize(new java.awt.Dimension(800, 600));
        pnl_arkaEkran.setPreferredSize(new java.awt.Dimension(800, 600));

        lbl_ayrim.setText("  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        pnl_log.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("Type the cell coordinate that you want to move: ");

        jLabel2.setText("Possible hit location(s): ");

        javax.swing.GroupLayout pnl_logLayout = new javax.swing.GroupLayout(pnl_log);
        pnl_log.setLayout(pnl_logLayout);
        pnl_logLayout.setHorizontalGroup(
            pnl_logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_logLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_logLayout.setVerticalGroup(
            pnl_logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_logLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_oyunEkrani.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnl_oyunEkraniLayout = new javax.swing.GroupLayout(pnl_oyunEkrani);
        pnl_oyunEkrani.setLayout(pnl_oyunEkraniLayout);
        pnl_oyunEkraniLayout.setHorizontalGroup(
            pnl_oyunEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        pnl_oyunEkraniLayout.setVerticalGroup(
            pnl_oyunEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        pnl_ustPanel.setBackground(new java.awt.Color(51, 51, 51));

        cmbx_butonSayisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "6", "7", "8", "9" }));

        btn_basla.setText("Start");
        btn_basla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_baslaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_ustPanelLayout = new javax.swing.GroupLayout(pnl_ustPanel);
        pnl_ustPanel.setLayout(pnl_ustPanelLayout);
        pnl_ustPanelLayout.setHorizontalGroup(
            pnl_ustPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ustPanelLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(cmbx_butonSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(btn_basla, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_ustPanelLayout.setVerticalGroup(
            pnl_ustPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ustPanelLayout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addGroup(pnl_ustPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_basla, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbx_butonSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout pnl_arkaEkranLayout = new javax.swing.GroupLayout(pnl_arkaEkran);
        pnl_arkaEkran.setLayout(pnl_arkaEkranLayout);
        pnl_arkaEkranLayout.setHorizontalGroup(
            pnl_arkaEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_arkaEkranLayout.createSequentialGroup()
                .addGroup(pnl_arkaEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_arkaEkranLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(pnl_oyunEkrani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnl_log, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_arkaEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pnl_ustPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_ayrim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_arkaEkranLayout.setVerticalGroup(
            pnl_arkaEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_arkaEkranLayout.createSequentialGroup()
                .addComponent(pnl_ustPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ayrim)
                .addGap(18, 18, 18)
                .addGroup(pnl_arkaEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_oyunEkrani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_arkaEkran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_arkaEkran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_baslaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_baslaActionPerformed
        // TODO add your handling code here:
        newGame();
    }//GEN-LAST:event_btn_baslaActionPerformed
    
    private void newGame() {
        
        pnl_oyunEkrani.removeAll();
        pnl_oyunEkrani.revalidate();
        pnl_oyunEkrani.repaint();
        String cmbxDegeri = cmbx_butonSayisi.getSelectedItem().toString();
        int butonSayisi = Integer.parseInt(cmbxDegeri);
        int bolme = pnl_oyunEkrani.getWidth() / butonSayisi;
        int harflendirme = 65;

        for (int i = 0; i < butonSayisi; i++) {
            for (int j = 0; j < butonSayisi; j++) {
                JButton buton = new JButton("x");
                if (i == 0 || j == 0) {
                    String panelDisiHarflendirme = "";
                    JLabel harf_label = new JLabel();

                    if (i == 0 && j == 0) {
                        panelDisiHarflendirme += j + 1;
                        harf_label.setText(panelDisiHarflendirme);
                        harf_label.setSize(20, 20);
                        pnl_arkaEkran.add(harf_label);
                        harf_label.setLocation((pnl_oyunEkrani.getX() + 20) + (bolme * j), pnl_oyunEkrani.getY() - 25);
                        panelDisiHarflendirme = "";
                        harf_label = new JLabel();
                        panelDisiHarflendirme += (char) (harflendirme + i);
                        harf_label.setText(panelDisiHarflendirme);
                        harf_label.setSize(20, 20);
                        pnl_arkaEkran.add(harf_label);
                        harf_label.setLocation(pnl_oyunEkrani.getX() - 20, pnl_oyunEkrani.getY() + (bolme * i) + 15);

                    } else if (i == 0) {
                        panelDisiHarflendirme += j + 1;
                        harf_label.setText(panelDisiHarflendirme);
                        harf_label.setSize(20, 20);
                        pnl_arkaEkran.add(harf_label);
                        harf_label.setLocation((pnl_oyunEkrani.getX() + 20) + (bolme * j), pnl_oyunEkrani.getY() - 25);
                    } else if (j == 0) {
                        panelDisiHarflendirme += (char) (harflendirme + i);
                        harf_label.setText(panelDisiHarflendirme);
                        harf_label.setSize(20, 20);
                        pnl_arkaEkran.add(harf_label);
                        harf_label.setLocation(pnl_oyunEkrani.getX() - 20, pnl_oyunEkrani.getY() + (bolme * i) + 15);
                    }
                }
                if (butonSayisi > 8) {
                    buton.setSize(40, 40);
                } else {
                    buton.setSize(50, 50);
                }

                if (butonSayisi % 2 == 1) {
                    if (butonSayisi / 2 == i && butonSayisi / 2 == j) {
                        pnl_oyunEkrani.add(buton);
                        buton.setLocation(bolme * i, bolme * j);
                        buton.setEnabled(false);
                        buton.setText("");
                    }
                    pnl_oyunEkrani.add(buton);
                    buton.setLocation(bolme * i, bolme * j);
                } else {
                    if ((butonSayisi / 2 == i && butonSayisi / 2 == j) || ((butonSayisi / 2) == i && (butonSayisi / 2) - 1 == j)
                            || ((butonSayisi / 2) - 1 == i && butonSayisi / 2 == j) || ((butonSayisi / 2) - 1 == i && (butonSayisi / 2) - 1 == j)) {
                        pnl_oyunEkrani.add(buton);
                        buton.setLocation(bolme * i, bolme * j);
                        buton.setEnabled(false);
                        buton.setText("");
                    }
                    pnl_oyunEkrani.add(buton);
                    buton.setLocation(bolme * i, bolme * j);
                }
            }

        }

        LinkedList<String> list = new LinkedList();
        list.createList(butonSayisi);
        list.deleteWhenGameStart(butonSayisi);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SoloNoble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SoloNoble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SoloNoble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SoloNoble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SoloNoble().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_basla;
    private javax.swing.JComboBox<String> cmbx_butonSayisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_ayrim;
    private javax.swing.JPanel pnl_arkaEkran;
    private javax.swing.JPanel pnl_log;
    private javax.swing.JPanel pnl_oyunEkrani;
    private javax.swing.JPanel pnl_ustPanel;
    // End of variables declaration//GEN-END:variables
}
