/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ogrencitakip;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mertc
 */
public class AkademisyenSayfasi extends javax.swing.JFrame {

    DefaultTableModel tbl_table_model;

    /**
     * Creates new form AkademisyenSayfasi
     */
    public AkademisyenSayfasi() {
        initComponents();
        tbl_table_model = new DefaultTableModel();
        tbl_table_model.setColumnIdentifiers(new Object[]{"ISIMSOYISIM", "EMAIL", "KULLANICIADI", "CINSIYET"});
        tbl_table.setModel(tbl_table_model);
        String url = "jdbc:derby://localhost:1527/Ogrenci_Takip";
        ResultSet rs = null;
        tbl_table_model.setRowCount(0);
        try {

            String query;
            Connection conn = DriverManager.getConnection(url, null, null);
            Statement stmt = conn.createStatement();

            query = "SELECT * FROM OGRENCI";
            rs = stmt.executeQuery(query);
            int id = rs.getInt(1) + 1;
            while (rs.next()) {
                String isimSoyisim = rs.getString("NAMESURNAME");
                String email = rs.getString("EMAIL");
                String username = rs.getString("KULLANICIADI");
                String cinsiyet = rs.getString("CINSIYET");
                tbl_table_model.addRow(new Object[]{isimSoyisim, email, username ,cinsiyet});
            }
            conn.close();

        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }

    public void tabloDoldurma() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_dersler = new javax.swing.JPanel();
        jCalendar = new com.toedter.calendar.JDayChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_ogrenciIsmi = new javax.swing.JTextField();
        btn_silme = new javax.swing.JButton();
        btn_arama = new javax.swing.JButton();
        cmbx_aramaYontemleri = new javax.swing.JComboBox<>();
        pnl_baslik = new javax.swing.JPanel();
        cmbx_akademisyenIslemler = new javax.swing.JComboBox<>();
        lbl_akademisyeniAdi = new javax.swing.JLabel();
        lbl_Takvim = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_sayfalar = new javax.swing.JMenu();
        menuItem_derslerim = new javax.swing.JMenuItem();
        menuItem_notGiris = new javax.swing.JMenuItem();
        menu_duzenleme = new javax.swing.JMenu();
        menuItem_altPanelRD = new javax.swing.JMenuItem();
        menuItem_ustPanelRD = new javax.swing.JMenuItem();
        menuItem_KisiselBilgiD = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        pnl_dersler.setBackground(new java.awt.Color(204, 255, 255));

        jCalendar.setDayBordersVisible(true);
        jCalendar.setDecorationBackgroundColor(new java.awt.Color(255, 153, 153));

        tbl_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_table);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Öğrenci Arama");

        btn_silme.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_silme.setText("SİLME");
        btn_silme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silmeActionPerformed(evt);
            }
        });

        btn_arama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_arama.setText("ARAMA");
        btn_arama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aramaActionPerformed(evt);
            }
        });

        cmbx_aramaYontemleri.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbx_aramaYontemleri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "İsim İle Arama", "Email İle Arama", "Kullanıcı Adı İle Arama", " ", " " }));

        javax.swing.GroupLayout pnl_derslerLayout = new javax.swing.GroupLayout(pnl_dersler);
        pnl_dersler.setLayout(pnl_derslerLayout);
        pnl_derslerLayout.setHorizontalGroup(
            pnl_derslerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_derslerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1396, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnl_derslerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(pnl_derslerLayout.createSequentialGroup()
                        .addGroup(pnl_derslerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_ogrenciIsmi, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_arama, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_derslerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbx_aramaYontemleri, 0, 230, Short.MAX_VALUE)
                            .addComponent(btn_silme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        pnl_derslerLayout.setVerticalGroup(
            pnl_derslerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_derslerLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(pnl_derslerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnl_derslerLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(pnl_derslerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbx_aramaYontemleri, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(txt_ogrenciIsmi))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_derslerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_silme, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_arama, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(126, 126, 126)
                        .addComponent(jCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(148, 148, 148))
        );

        pnl_baslik.setBackground(new java.awt.Color(204, 255, 204));

        cmbx_akademisyenIslemler.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbx_akademisyenIslemler.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kontrol Paneli", "Notlar", "Çıkış Yap" }));
        cmbx_akademisyenIslemler.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbx_akademisyenIslemlerİtemStateChanged(evt);
            }
        });

        lbl_akademisyeniAdi.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_akademisyeniAdi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_akademisyeniAdi.setText("Mertcan Karabaş");

        lbl_Takvim.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbl_Takvim.setText("Kontrol Paneli");

        javax.swing.GroupLayout pnl_baslikLayout = new javax.swing.GroupLayout(pnl_baslik);
        pnl_baslik.setLayout(pnl_baslikLayout);
        pnl_baslikLayout.setHorizontalGroup(
            pnl_baslikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_baslikLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(lbl_Takvim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_baslikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_akademisyeniAdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbx_akademisyenIslemler, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        pnl_baslikLayout.setVerticalGroup(
            pnl_baslikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_baslikLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(pnl_baslikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_baslikLayout.createSequentialGroup()
                        .addComponent(lbl_Takvim)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_baslikLayout.createSequentialGroup()
                        .addComponent(lbl_akademisyeniAdi)
                        .addGap(18, 18, 18)
                        .addComponent(cmbx_akademisyenIslemler, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );

        menu_sayfalar.setText("Sayfalar");

        menuItem_derslerim.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItem_derslerim.setText("Derslerim");
        menu_sayfalar.add(menuItem_derslerim);

        menuItem_notGiris.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItem_notGiris.setText("Not Girişi");
        menu_sayfalar.add(menuItem_notGiris);

        jMenuBar1.add(menu_sayfalar);

        menu_duzenleme.setText("Düzenleme");

        menuItem_altPanelRD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItem_altPanelRD.setText("Alt Panel Renk Değiştirme");
        menuItem_altPanelRD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_altPanelRDActionPerformed(evt);
            }
        });
        menu_duzenleme.add(menuItem_altPanelRD);

        menuItem_ustPanelRD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItem_ustPanelRD.setText("Üst Panel Renk Değiştirme");
        menuItem_ustPanelRD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_ustPanelRDActionPerformed(evt);
            }
        });
        menu_duzenleme.add(menuItem_ustPanelRD);

        menuItem_KisiselBilgiD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItem_KisiselBilgiD.setText("Kişisel Bilgileri Değiştirme");
        menuItem_KisiselBilgiD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_KisiselBilgiDActionPerformed(evt);
            }
        });
        menu_duzenleme.add(menuItem_KisiselBilgiD);

        jMenuBar1.add(menu_duzenleme);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_baslik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pnl_dersler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_baslik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_dersler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbx_akademisyenIslemlerİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbx_akademisyenIslemlerİtemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == 2) {
            return;
        }
        if (cmbx_akademisyenIslemler.getSelectedItem().toString().equals("Notlar")) {
            aDerslerim frame = new aDerslerim();
            frame.setVisible(true);
            this.dispose();
        } else if (cmbx_akademisyenIslemler.getSelectedItem().toString().equals("Çıkış Yap")) {
            IlkSayfa frame = new IlkSayfa();
            frame.setVisible(true);
            this.dispose();
        } else if (cmbx_akademisyenIslemler.getSelectedItem().toString().equals("Kontrol Paneli")) {
            AkademisyenSayfasi frame = new AkademisyenSayfasi();
            frame.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_cmbx_akademisyenIslemlerİtemStateChanged

    private void menuItem_altPanelRDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_altPanelRDActionPerformed
        // TODO add your handling code here:
        Color color = JColorChooser.showDialog(this, "Bir renk seciniz ", Color.WHITE);
        pnl_dersler.setBackground(color);
    }//GEN-LAST:event_menuItem_altPanelRDActionPerformed

    private void menuItem_ustPanelRDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_ustPanelRDActionPerformed
        // TODO add your handling code here:
        Color color = JColorChooser.showDialog(this, "Bir renk seciniz ", Color.WHITE);
        pnl_baslik.setBackground(color);
    }//GEN-LAST:event_menuItem_ustPanelRDActionPerformed

    private void menuItem_KisiselBilgiDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_KisiselBilgiDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItem_KisiselBilgiDActionPerformed

    private void btn_silmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silmeActionPerformed
        // TODO add your handling code here:
        String email = (String) tbl_table.getValueAt(tbl_table.getSelectedRow(), 1);
        OgrenciTakipDB.emailIleSilme(email);
        tbl_table_model.removeRow(tbl_table.getSelectedRow());
    }//GEN-LAST:event_btn_silmeActionPerformed

    private void btn_aramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aramaActionPerformed
        // TODO add your handling code here:
        if (cmbx_aramaYontemleri.getSelectedItem().toString().equals("Email İle Arama")) {
            String email = txt_ogrenciIsmi.getText();
            OgrenciTakipDB.emailIleArama(email, tbl_table_model);
        } else if (cmbx_aramaYontemleri.getSelectedItem().toString().equals("İsim İle Arama"))  {
            String nameSurname = txt_ogrenciIsmi.getText();
            OgrenciTakipDB.isimIleArama(nameSurname, tbl_table_model);
        } else if (cmbx_aramaYontemleri.getSelectedItem().toString().equals("Kullanıcı Adı İle Arama")) {
            String kullaniciAdi = txt_ogrenciIsmi.getText();
            OgrenciTakipDB.kullaniciAdiIleArama(kullaniciAdi, tbl_table_model);
        }

    }//GEN-LAST:event_btn_aramaActionPerformed

    private void tbl_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tableMouseClicked
        // TODO add your handling code here:
        String email = (String) tbl_table.getValueAt(tbl_table.getSelectedRow(), 0);

    }//GEN-LAST:event_tbl_tableMouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_arama;
    private javax.swing.JButton btn_silme;
    private javax.swing.JComboBox<String> cmbx_akademisyenIslemler;
    private javax.swing.JComboBox<String> cmbx_aramaYontemleri;
    private com.toedter.calendar.JDayChooser jCalendar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Takvim;
    private javax.swing.JLabel lbl_akademisyeniAdi;
    private javax.swing.JMenuItem menuItem_KisiselBilgiD;
    private javax.swing.JMenuItem menuItem_altPanelRD;
    private javax.swing.JMenuItem menuItem_derslerim;
    private javax.swing.JMenuItem menuItem_notGiris;
    private javax.swing.JMenuItem menuItem_ustPanelRD;
    private javax.swing.JMenu menu_duzenleme;
    private javax.swing.JMenu menu_sayfalar;
    private javax.swing.JPanel pnl_baslik;
    private javax.swing.JPanel pnl_dersler;
    private javax.swing.JTable tbl_table;
    private javax.swing.JTextField txt_ogrenciIsmi;
    // End of variables declaration//GEN-END:variables
}
