/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ogrencitakip;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.naming.spi.DirStateFactory;

/**
 *
 * @author mertc
 */
public class aKayitSayfasi extends javax.swing.JFrame {

    /**
     * Creates new form aKayitSayfasi
     */
    public aKayitSayfasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cinsiyetButonGrup = new javax.swing.ButtonGroup();
        gorevButonGrup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbl_kayitSayfasi = new javax.swing.JLabel();
        lbl_isim = new javax.swing.JLabel();
        txt_isim = new javax.swing.JTextField();
        lbl_soyisim = new javax.swing.JLabel();
        txt_soyisim = new javax.swing.JTextField();
        lbl_eMail = new javax.swing.JLabel();
        txt_eMail = new javax.swing.JTextField();
        lbl_kullaniciAdi = new javax.swing.JLabel();
        txt_kullaniciAdi = new javax.swing.JTextField();
        lbl_sifre = new javax.swing.JLabel();
        pswd_sifre = new javax.swing.JPasswordField();
        lbl_sifreTekrar = new javax.swing.JLabel();
        pswd_sifreTekrar = new javax.swing.JPasswordField();
        lbl_guvenlikSorusu = new javax.swing.JLabel();
        cmbx_guvenlikSorulari = new javax.swing.JComboBox<>();
        lbl_gSorusuCevap = new javax.swing.JLabel();
        txt_gSorusuCevap = new javax.swing.JTextField();
        lbl_cinsiyet = new javax.swing.JLabel();
        rb_erkek = new javax.swing.JRadioButton();
        rb_kadın = new javax.swing.JRadioButton();
        lbl_gorev = new javax.swing.JLabel();
        rb_ogrenci = new javax.swing.JRadioButton();
        rb_akademisyen = new javax.swing.JRadioButton();
        lbl_isimHata = new javax.swing.JLabel();
        lbl_soyisimHata = new javax.swing.JLabel();
        lbl_kullaniciAdiHata = new javax.swing.JLabel();
        lbl_sifreHata = new javax.swing.JLabel();
        lbl_sifreTekrarHata = new javax.swing.JLabel();
        lbl_emailHata = new javax.swing.JLabel();
        lbl_gSorusuCevapHata = new javax.swing.JLabel();
        btn_kayitOl = new javax.swing.JButton();
        lbl_girisYap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));

        lbl_kayitSayfasi.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        lbl_kayitSayfasi.setText("Kayıt Sayfası");

        lbl_isim.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_isim.setText("İsim");

        lbl_soyisim.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_soyisim.setText("Soyisim");

        lbl_eMail.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_eMail.setText("E-mail");

        lbl_kullaniciAdi.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_kullaniciAdi.setText("Kullanıcı Adı");

        lbl_sifre.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_sifre.setText("Şifre");

        lbl_sifreTekrar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_sifreTekrar.setText("Şifre Tekrar");

        lbl_guvenlikSorusu.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_guvenlikSorusu.setText("Güvenlik Sorusu Seçiniz");

        cmbx_guvenlikSorulari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "İlk Evcil Hayvanızın Adı?", "İlkolkul Öğretmeninizin Adı?", "En Sevdiğiniz Çiçek?", "Annenizin Kızlık Soyadı?", "En Sevdiğiniz Oyun?", "En Sevdiğiniz Kitap?" }));

        lbl_gSorusuCevap.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_gSorusuCevap.setText("Cevabınız");

        lbl_cinsiyet.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_cinsiyet.setText("Cinsiyet");

        cinsiyetButonGrup.add(rb_erkek);
        rb_erkek.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb_erkek.setSelected(true);
        rb_erkek.setText("Erkek");

        cinsiyetButonGrup.add(rb_kadın);
        rb_kadın.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb_kadın.setText("Kadın");

        lbl_gorev.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_gorev.setText("Görev");

        gorevButonGrup.add(rb_ogrenci);
        rb_ogrenci.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb_ogrenci.setSelected(true);
        rb_ogrenci.setText("Öğrenci");

        gorevButonGrup.add(rb_akademisyen);
        rb_akademisyen.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb_akademisyen.setText("Akademisyen");

        btn_kayitOl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_kayitOl.setText("Kayıt Ol");
        btn_kayitOl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayitOlActionPerformed(evt);
            }
        });

        lbl_girisYap.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_girisYap.setText("Zaten Bir Hesabınız Var Mı? Giriş Yap");
        lbl_girisYap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_girisYapMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_guvenlikSorusu)
                                    .addComponent(lbl_kullaniciAdi)
                                    .addComponent(lbl_isim)
                                    .addComponent(lbl_sifre)
                                    .addComponent(lbl_soyisim)
                                    .addComponent(lbl_sifreTekrar)
                                    .addComponent(lbl_eMail)
                                    .addComponent(lbl_gSorusuCevap)
                                    .addComponent(lbl_cinsiyet)
                                    .addComponent(lbl_gorev))
                                .addGap(115, 170, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_gSorusuCevap, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_eMail, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_isim)
                                    .addComponent(txt_soyisim)
                                    .addComponent(txt_kullaniciAdi)
                                    .addComponent(pswd_sifre)
                                    .addComponent(pswd_sifreTekrar)
                                    .addComponent(cmbx_guvenlikSorulari, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rb_ogrenci)
                                            .addComponent(rb_erkek))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rb_kadın)
                                            .addComponent(rb_akademisyen))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(129, 129, 129)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lbl_soyisimHata, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbl_isimHata, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbl_sifreHata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbl_sifreTekrarHata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbl_emailHata, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_gSorusuCevapHata, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_kullaniciAdiHata, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(266, 266, 266)
                                .addComponent(lbl_kayitSayfasi)))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_girisYap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_kayitOl, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(385, 385, 385))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lbl_kayitSayfasi)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_isim)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_soyisim))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_isimHata, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_soyisimHata, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lbl_kullaniciAdi))
                            .addComponent(lbl_kullaniciAdiHata, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_isim, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_soyisim, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_kullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pswd_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_sifre))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pswd_sifreTekrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_sifreTekrar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_sifreHata, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_sifreTekrarHata, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_eMail, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_eMail))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbx_guvenlikSorulari, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_guvenlikSorusu)))
                    .addComponent(lbl_emailHata, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_gSorusuCevapHata, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_kayitOl, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_gSorusuCevap, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_gSorusuCevap))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_cinsiyet)
                                    .addComponent(rb_erkek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rb_kadın))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_gorev)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rb_ogrenci)
                                        .addComponent(rb_akademisyen)))
                                .addGap(86, 86, 86)
                                .addComponent(lbl_girisYap)))
                        .addContainerGap(145, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1930, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kayitOlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayitOlActionPerformed
        // TODO add your handling code here:
        Matcher matcher;

        if (txt_isim.getText().isEmpty()) {
            lbl_isimHata.setText("İsim boş olamaz.");
            lbl_isimHata.setVisible(true);
            return;
        } else {
            matcher = Pattern.compile("^[A-Za-z]\\w{2,29}$").matcher(txt_isim.getText());
            if (!matcher.find()) {
                lbl_isimHata.setText("İsminiz en az 2 karakterden oluşabilir.");
                lbl_isimHata.setVisible(true);
                return;
            } else {
                lbl_isimHata.setVisible(false);
            }
        }

        if (txt_soyisim.getText().isEmpty()) {
            lbl_soyisimHata.setText("İsim boş olamaz.");
            lbl_soyisimHata.setVisible(true);
            return;
        } else {
            matcher = Pattern.compile("^\\w{2,}$").matcher(txt_soyisim.getText());
            if (!matcher.find()) {
                lbl_soyisimHata.setText("Soyisminiz en az 2 karakterden oluşabilir.");
                lbl_soyisimHata.setVisible(true);
                return;
            } else {
                lbl_soyisimHata.setVisible(false);
            }
        }

        if (txt_kullaniciAdi.getText().isEmpty()) {
            lbl_kullaniciAdiHata.setText("Kullanıcı adı boş olamaz.");
            lbl_kullaniciAdiHata.setVisible(true);
            return;
        } else {
            matcher = Pattern.compile("^\\w{3,}$").matcher(txt_kullaniciAdi.getText());
            if (!matcher.find()) {
                lbl_kullaniciAdiHata.setText("Kullanıcı adı en az 3 karakterden oluşabilir.");
                lbl_kullaniciAdiHata.setVisible(true);
                return;
            } else {
                lbl_kullaniciAdiHata.setVisible(false);
            }
        }
        
        if ((OgrenciTakipDB.ogrenciKullaniciAdiKontrol(txt_kullaniciAdi.getText())) || (OgrenciTakipDB.akademisyenKullaniciAdiKontrol(txt_kullaniciAdi.getText()))) {
            lbl_kullaniciAdiHata.setText("Bu kullanıcı adı zaten mevcut");
            lbl_kullaniciAdiHata.setVisible(true);
            return;
        } else {
            lbl_kullaniciAdiHata.setVisible(false);
        }

        if (pswd_sifre.getText().isEmpty()) {
            lbl_sifreHata.setText("Şifre boş olamaz.");
            lbl_sifreHata.setVisible(true);
            return;
        } else {
            matcher = Pattern.compile("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#&()–[{}]:;',?/*~$^+=<>]).{8,20}$").matcher(pswd_sifre.getText());
            if (!matcher.find()) {
                lbl_sifreHata.setText("Şifreniz 8-20 karakter arası olmalı.\n"
                        + "En az bir büyük bir küçük harf ve bir rakam barındırmalıdır. "
                        + "İçinde özel karakter olmalıdır(!@#&()–[{}]:;',?/*~$^+=<>).");
                lbl_sifreHata.setVisible(true);
                return;
            } else {
                lbl_sifreHata.setVisible(false);
            }
        }

        if (pswd_sifreTekrar.getText().isEmpty()) {
            lbl_sifreTekrarHata.setText("Şifre tekrar boş olamaz.");
            lbl_sifreTekrarHata.setVisible(true);
            return;
        } else {
            if (pswd_sifre.getPassword().equals(pswd_sifreTekrar.getPassword())) {
                lbl_sifreTekrarHata.setText("Şifreleriniz uyuşmuyor.");
                lbl_sifreTekrarHata.setVisible(true);
                return;
            } else {
                lbl_sifreTekrarHata.setVisible(false);
            }
        }

        if (txt_eMail.getText().isEmpty()) {
            lbl_emailHata.setText("E-mail boş olamaz.");
            lbl_emailHata.setVisible(true);
            return;
        } else {
            matcher = Pattern.compile("^(.+)@(.+)$").matcher(txt_eMail.getText());
            if (!matcher.find()) {
                lbl_emailHata.setText("E-mailinizi doğru giriniz.");
                lbl_emailHata.setVisible(true);
                return;
            } else {
                lbl_emailHata.setVisible(false);
            }
        }
        
         if ((OgrenciTakipDB.akademisyenEmailKontrol(txt_eMail.getText())) || (OgrenciTakipDB.ogrenciEmailKontrol(txt_eMail.getText()))) {
            lbl_emailHata.setText("Bu email zaten mevcut");
            lbl_emailHata.setVisible(true);
            return;
        } else {
            lbl_emailHata.setVisible(false);
        }
         
        if (txt_gSorusuCevap.getText().isEmpty()) {
            lbl_gSorusuCevapHata.setText("Güvenlik sorusu cevabı boş olamaz.");
            lbl_gSorusuCevapHata.setVisible(true);
            return;
        } else {
            lbl_gSorusuCevapHata.setVisible(false);
        }

        String eMail = txt_eMail.getText();
        String nameSurname = txt_isim.getText() + " " + txt_soyisim.getText();
        String kullaniciAdi = txt_kullaniciAdi.getText();
        String sifre = new String(pswd_sifre.getPassword());
        String guvenlikSorusu = cmbx_guvenlikSorulari.getSelectedItem().toString();
        String gSorusuCevap = txt_gSorusuCevap.getText();
        boolean isAkademisyen = rb_akademisyen.isSelected();
        char cinsiyet;

        if (rb_erkek.isSelected()) {
            cinsiyet = 'E';
        } else {
            cinsiyet = 'K';
        }

        OgrenciTakipDB.kullaniciEkleme(isAkademisyen, eMail, nameSurname, kullaniciAdi, sifre, guvenlikSorusu, gSorusuCevap, cinsiyet);

        if (rb_ogrenci.isSelected()) {
            OgrenciGiris frame = new OgrenciGiris();
            frame.setVisible(true);
            this.dispose();
        } else {
            AkademisyenGiris frame = new AkademisyenGiris();
            frame.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_kayitOlActionPerformed

    private void lbl_girisYapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_girisYapMouseClicked
        // TODO add your handling code here:
        AkademisyenGiris frame = new AkademisyenGiris();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_girisYapMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kayitOl;
    private javax.swing.ButtonGroup cinsiyetButonGrup;
    private javax.swing.JComboBox<String> cmbx_guvenlikSorulari;
    private javax.swing.ButtonGroup gorevButonGrup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_cinsiyet;
    private javax.swing.JLabel lbl_eMail;
    private javax.swing.JLabel lbl_emailHata;
    private javax.swing.JLabel lbl_gSorusuCevap;
    private javax.swing.JLabel lbl_gSorusuCevapHata;
    private javax.swing.JLabel lbl_girisYap;
    private javax.swing.JLabel lbl_gorev;
    private javax.swing.JLabel lbl_guvenlikSorusu;
    private javax.swing.JLabel lbl_isim;
    private javax.swing.JLabel lbl_isimHata;
    private javax.swing.JLabel lbl_kayitSayfasi;
    private javax.swing.JLabel lbl_kullaniciAdi;
    private javax.swing.JLabel lbl_kullaniciAdiHata;
    private javax.swing.JLabel lbl_sifre;
    private javax.swing.JLabel lbl_sifreHata;
    private javax.swing.JLabel lbl_sifreTekrar;
    private javax.swing.JLabel lbl_sifreTekrarHata;
    private javax.swing.JLabel lbl_soyisim;
    private javax.swing.JLabel lbl_soyisimHata;
    private javax.swing.JPasswordField pswd_sifre;
    private javax.swing.JPasswordField pswd_sifreTekrar;
    private javax.swing.JRadioButton rb_akademisyen;
    private javax.swing.JRadioButton rb_erkek;
    private javax.swing.JRadioButton rb_kadın;
    private javax.swing.JRadioButton rb_ogrenci;
    private javax.swing.JTextField txt_eMail;
    private javax.swing.JTextField txt_gSorusuCevap;
    private javax.swing.JTextField txt_isim;
    private javax.swing.JTextField txt_kullaniciAdi;
    private javax.swing.JTextField txt_soyisim;
    // End of variables declaration//GEN-END:variables
}
