/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ogrencitakip;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author mertc
 */
public class aSifreYenileme extends javax.swing.JFrame {
   
    String email;
    /**
     * Creates new form ŞifreYenileme
     */
    public aSifreYenileme(Akademisyen akademisyen) {
        initComponents();
        email = akademisyen.email;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_sifre = new javax.swing.JLabel();
        pswd_sifre = new javax.swing.JPasswordField();
        lbl_sifreTekrar = new javax.swing.JLabel();
        pswd_sifreTekrar = new javax.swing.JPasswordField();
        btn_gonder = new javax.swing.JButton();
        lbl_sifreHata = new javax.swing.JLabel();
        lbl_sifreTekrarHata = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));

        lbl_sifre.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_sifre.setText("Yeni Şifreyi Giriniz");

        pswd_sifre.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        lbl_sifreTekrar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_sifreTekrar.setText("Şifre Tekrar");

        pswd_sifreTekrar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        btn_gonder.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_gonder.setText("Gönder");
        btn_gonder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gonderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(376, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_sifre)
                    .addComponent(lbl_sifreTekrar))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pswd_sifre)
                            .addComponent(pswd_sifreTekrar, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_sifreTekrarHata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_sifreHata, javax.swing.GroupLayout.PREFERRED_SIZE, 1053, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btn_gonder, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_sifreHata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pswd_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_sifre)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_sifreTekrarHata, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pswd_sifreTekrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_sifreTekrar)))
                .addGap(79, 79, 79)
                .addComponent(btn_gonder, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(386, 386, 386))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gonderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gonderActionPerformed
        // TODO add your handling code here:
        Matcher matcher;
        
        if (pswd_sifre.getText().isEmpty()) {
            lbl_sifreHata.setText("Şifre boş olamaz.");
            lbl_sifreHata.setVisible(true);
            return;
        } else {
            matcher = Pattern.compile("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#&()–[{}]:;',?/*~$^+=<>]).{8,20}$").matcher(pswd_sifre.getText());
            if (!matcher.find()) {
                lbl_sifreHata.setText("Şifreniz 8-20 karakter arası olmalı.\n"
                        + "En az bir büyük bir küçük harf ve bir rakam barındırmalıdır. "
                        + "İçinde özel karakter olmalıdır(!@#&()–[{}]:;',?/*~$^+=<>).");
                lbl_sifreHata.setVisible(true);
                return;
            } else {
                lbl_sifreHata.setVisible(false);
            }
        }

        if (pswd_sifreTekrar.getText().isEmpty()) {
            lbl_sifreTekrarHata.setText("İsim boş olamaz.");
            lbl_sifreTekrarHata.setVisible(true);
            return;
        } else {
            if (pswd_sifre.getPassword().equals(pswd_sifreTekrar.getPassword())) {
                lbl_sifreTekrarHata.setText("Şifreleriniz uyuşmuyor.");
                lbl_sifreTekrarHata.setVisible(true);
                return;
            } else {
                lbl_sifreTekrarHata.setVisible(false);
            }
        }
        
        String sifre = new String(pswd_sifre.getPassword());
        Akademisyen secilenAkademisyen = new Akademisyen();
        OgrenciTakipDB.akademisyenSifreGuncelleme(secilenAkademisyen);
        JOptionPane.showMessageDialog(this, "İşlem başarıyla gerçekleşti.");
        
        AkademisyenGiris frame = new AkademisyenGiris();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_gonderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_gonder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_sifre;
    private javax.swing.JLabel lbl_sifreHata;
    private javax.swing.JLabel lbl_sifreTekrar;
    private javax.swing.JLabel lbl_sifreTekrarHata;
    private javax.swing.JPasswordField pswd_sifre;
    private javax.swing.JPasswordField pswd_sifreTekrar;
    // End of variables declaration//GEN-END:variables
}
