/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ogrencitakip;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author mertc
 */
public class OgrenciSayfasi extends javax.swing.JFrame {

    /**
     * Creates new form OgrenciSayfasi
     */
    public OgrenciSayfasi() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_ogrenciAdi = new javax.swing.JLabel();
        pnl_dersler = new javax.swing.JPanel();
        jCalendar = new com.toedter.calendar.JDayChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnl_baslik = new javax.swing.JPanel();
        cmbx_ogrenciIslemler = new javax.swing.JComboBox<>();
        lbl_kontrolPaneli = new javax.swing.JLabel();
        lbl_ogrenciIsim = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_sayfalar = new javax.swing.JMenu();
        menuItem_derslerim = new javax.swing.JMenuItem();
        menuItem_Notlarım = new javax.swing.JMenuItem();
        menu_duzenleme = new javax.swing.JMenu();
        menuItem_altPanelRD = new javax.swing.JMenuItem();
        menuItem_ustPanelRD = new javax.swing.JMenuItem();
        menuItem_KisiselBilgiD = new javax.swing.JMenuItem();

        lbl_ogrenciAdi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_ogrenciAdi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ogrenciAdi.setText("Mertcan Karabaş");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        pnl_dersler.setBackground(new java.awt.Color(204, 255, 255));

        jCalendar.setDayBordersVisible(true);
        jCalendar.setDecorationBackgroundColor(new java.awt.Color(255, 153, 153));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pnl_derslerLayout = new javax.swing.GroupLayout(pnl_dersler);
        pnl_dersler.setLayout(pnl_derslerLayout);
        pnl_derslerLayout.setHorizontalGroup(
            pnl_derslerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_derslerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_derslerLayout.setVerticalGroup(
            pnl_derslerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_derslerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_derslerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_derslerLayout.createSequentialGroup()
                        .addGap(0, 364, Short.MAX_VALUE)
                        .addComponent(jCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pnl_baslik.setBackground(new java.awt.Color(204, 255, 204));

        cmbx_ogrenciIslemler.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbx_ogrenciIslemler.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kontrol Paneli", "Notlar", "Çıkış Yap" }));
        cmbx_ogrenciIslemler.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbx_ogrenciIslemlerİtemStateChanged(evt);
            }
        });

        lbl_kontrolPaneli.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbl_kontrolPaneli.setText("Kontrol Paneli");

        lbl_ogrenciIsim.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_ogrenciIsim.setText("Mertcan Karabaş");

        javax.swing.GroupLayout pnl_baslikLayout = new javax.swing.GroupLayout(pnl_baslik);
        pnl_baslik.setLayout(pnl_baslikLayout);
        pnl_baslikLayout.setHorizontalGroup(
            pnl_baslikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_baslikLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(lbl_kontrolPaneli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_baslikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbx_ogrenciIslemler, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ogrenciIsim))
                .addGap(49, 49, 49))
        );
        pnl_baslikLayout.setVerticalGroup(
            pnl_baslikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_baslikLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(pnl_baslikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_kontrolPaneli, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_baslikLayout.createSequentialGroup()
                        .addComponent(lbl_ogrenciIsim)
                        .addGap(18, 18, 18)
                        .addComponent(cmbx_ogrenciIslemler, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );

        menu_sayfalar.setText("Sayfalar");

        menuItem_derslerim.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItem_derslerim.setText("Derslerim");
        menu_sayfalar.add(menuItem_derslerim);

        menuItem_Notlarım.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItem_Notlarım.setText("Notlarım");
        menu_sayfalar.add(menuItem_Notlarım);

        jMenuBar1.add(menu_sayfalar);

        menu_duzenleme.setText("Düzenleme");

        menuItem_altPanelRD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItem_altPanelRD.setText("Alt Panel Renk Değiştirme");
        menuItem_altPanelRD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_altPanelRDActionPerformed(evt);
            }
        });
        menu_duzenleme.add(menuItem_altPanelRD);

        menuItem_ustPanelRD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItem_ustPanelRD.setText("Üst Panel Renk Değiştirme");
        menuItem_ustPanelRD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_ustPanelRDActionPerformed(evt);
            }
        });
        menu_duzenleme.add(menuItem_ustPanelRD);

        menuItem_KisiselBilgiD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItem_KisiselBilgiD.setText("Kişisel Bilgileri Değiştirme");
        menuItem_KisiselBilgiD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_KisiselBilgiDActionPerformed(evt);
            }
        });
        menu_duzenleme.add(menuItem_KisiselBilgiD);

        jMenuBar1.add(menu_duzenleme);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_baslik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_dersler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_baslik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_dersler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem_altPanelRDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_altPanelRDActionPerformed
        // TODO add your handling code here:
        Color color = JColorChooser.showDialog(this, "Bir renk seciniz ", Color.WHITE);
        pnl_dersler.setBackground(color);
    }//GEN-LAST:event_menuItem_altPanelRDActionPerformed

    private void menuItem_ustPanelRDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_ustPanelRDActionPerformed
        // TODO add your handling code here:
        Color color = JColorChooser.showDialog(this, "Bir renk seciniz ", Color.WHITE);
        pnl_baslik.setBackground(color);
    }//GEN-LAST:event_menuItem_ustPanelRDActionPerformed

    private void menuItem_KisiselBilgiDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_KisiselBilgiDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItem_KisiselBilgiDActionPerformed

    private void cmbx_ogrenciIslemlerİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbx_ogrenciIslemlerİtemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == 2) {
            return;
        }
        if (cmbx_ogrenciIslemler.getSelectedItem().toString().equals("Notlar")) {
            aDerslerim frame = new aDerslerim();
            frame.setVisible(true);
            this.dispose();
        } else if (cmbx_ogrenciIslemler.getSelectedItem().toString().equals("Çıkış Yap")) {
            IlkSayfa frame = new IlkSayfa();
            frame.setVisible(true);
            this.dispose();
        } else if (cmbx_ogrenciIslemler.getSelectedItem().toString().equals("Kontrol Paneli")) {
            OgrenciSayfasi frame = new OgrenciSayfasi();
            frame.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_cmbx_ogrenciIslemlerİtemStateChanged
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbx_ogrenciIslemler;
    private com.toedter.calendar.JDayChooser jCalendar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_kontrolPaneli;
    private javax.swing.JLabel lbl_ogrenciAdi;
    private javax.swing.JLabel lbl_ogrenciIsim;
    private javax.swing.JMenuItem menuItem_KisiselBilgiD;
    private javax.swing.JMenuItem menuItem_Notlarım;
    private javax.swing.JMenuItem menuItem_altPanelRD;
    private javax.swing.JMenuItem menuItem_derslerim;
    private javax.swing.JMenuItem menuItem_ustPanelRD;
    private javax.swing.JMenu menu_duzenleme;
    private javax.swing.JMenu menu_sayfalar;
    private javax.swing.JPanel pnl_baslik;
    private javax.swing.JPanel pnl_dersler;
    // End of variables declaration//GEN-END:variables
}
