/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ogrencitakip;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.naming.spi.DirStateFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author mertc
 */
public class OgrenciGiris extends javax.swing.JFrame {

    /**
     * Creates new form OgrenciGiris
     */
    public OgrenciGiris() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_ogrenciKullaniciAdi = new javax.swing.JTextField();
        pswd_ogrenciSifre = new javax.swing.JPasswordField();
        btn_girisYap = new javax.swing.JButton();
        btn_kayitOl = new javax.swing.JButton();
        lbl_sifremiUnuttum = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_geri = new javax.swing.JButton();
        chbx_sifreyiGoster = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));

        txt_ogrenciKullaniciAdi.setText("Kullanıcı Adı");
        txt_ogrenciKullaniciAdi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_ogrenciKullaniciAdiMouseEntered(evt);
            }
        });

        btn_girisYap.setText("Giriş Yap");
        btn_girisYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girisYapActionPerformed(evt);
            }
        });

        btn_kayitOl.setText("Kayıt Ol");
        btn_kayitOl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayitOlActionPerformed(evt);
            }
        });

        lbl_sifremiUnuttum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_sifremiUnuttum.setText("Şifremi Unuttum");
        lbl_sifremiUnuttum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_sifremiUnuttumMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("ÖĞRENCİ GİRİŞ EKRANI");

        btn_geri.setText("Akademisyen Giriş Ekranına Git");
        btn_geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_geriActionPerformed(evt);
            }
        });

        chbx_sifreyiGoster.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chbx_sifreyiGoster.setText("Şifreyi Göster");
        chbx_sifreyiGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbx_sifreyiGosterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btn_geri, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(670, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_sifremiUnuttum)
                            .addComponent(chbx_sifreyiGoster, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pswd_ogrenciSifre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ogrenciKullaniciAdi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_girisYap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_kayitOl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(654, 654, 654))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(txt_ogrenciKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pswd_ogrenciSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chbx_sifreyiGoster)
                .addGap(18, 18, 18)
                .addComponent(btn_girisYap, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_sifremiUnuttum)
                .addGap(18, 18, 18)
                .addComponent(btn_kayitOl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195)
                .addComponent(btn_geri, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_sifremiUnuttumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_sifremiUnuttumMouseClicked
        // TODO add your handling code here:
        aSifremiUnuttum frame = new aSifremiUnuttum();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lbl_sifremiUnuttumMouseClicked

    private void btn_kayitOlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayitOlActionPerformed
        // TODO add your handling code here:
        oKayitSayfasi frame = new oKayitSayfasi();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_kayitOlActionPerformed

    private void txt_ogrenciKullaniciAdiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ogrenciKullaniciAdiMouseEntered
        // TODO add your handling code here:
        if (txt_ogrenciKullaniciAdi.getText().equals("Kullanıcı Adı")) {
            txt_ogrenciKullaniciAdi.setText("");
        } 
    }//GEN-LAST:event_txt_ogrenciKullaniciAdiMouseEntered

    private void btn_girisYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_girisYapActionPerformed
        // TODO add your handling code here:
        String username = txt_ogrenciKullaniciAdi.getText();
        String password = new String(pswd_ogrenciSifre.getPassword());
        String url = "jdbc:derby://localhost:1527/Ogrenci_Takip";
        
        try{
            Connection conn = DriverManager.getConnection(url);
            Statement stmt = conn.createStatement();
            String query = "SELECT * FROM OGRENCI WHERE KULLANICIADI = '" + username + "' AND SIFRE = '" + password + "'";
            ResultSet rs = stmt.executeQuery(query);
            
            if (rs.next()) {
                OgrenciSayfasi frame = new OgrenciSayfasi();
                frame.setVisible(true);
                this.dispose();
            
            } else {
                JOptionPane.showMessageDialog(this, "Kullanıcı adını veya Şifrenizi yanlış girdiniz. Tekrar deneyiniz.");
                txt_ogrenciKullaniciAdi.setText("");
                pswd_ogrenciSifre.setText("");
            }
       
        } catch (Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btn_girisYapActionPerformed

    private void btn_geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_geriActionPerformed
        // TODO add your handling code here:
        AkademisyenGiris frame = new AkademisyenGiris();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_geriActionPerformed

    private void chbx_sifreyiGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbx_sifreyiGosterActionPerformed
        // TODO add your handling code here:
        if (chbx_sifreyiGoster.isSelected()) 
            pswd_ogrenciSifre.setEchoChar((char)0);
        else
            pswd_ogrenciSifre.setEchoChar('*');
    }//GEN-LAST:event_chbx_sifreyiGosterActionPerformed
 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_geri;
    private javax.swing.JButton btn_girisYap;
    private javax.swing.JButton btn_kayitOl;
    private javax.swing.JCheckBox chbx_sifreyiGoster;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_sifremiUnuttum;
    private javax.swing.JPasswordField pswd_ogrenciSifre;
    private javax.swing.JTextField txt_ogrenciKullaniciAdi;
    // End of variables declaration//GEN-END:variables
}
