/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ogrencitakip;

import javax.swing.JOptionPane;

/**
 *
 * @author mertc
 */
public class oSifremiUnuttumDevam extends javax.swing.JFrame {
    
    String email;
    /**
     * Creates new form SifremiUnuttumDevaö
     */
    public oSifremiUnuttumDevam(Ogrenci ogrenci) {
        initComponents();
        Ogrenci seciliOgrenci = OgrenciTakipDB.kullaniciAdiİleOgrenciBilgileriAlma(ogrenci.kullaniciAdi);
        this.email = seciliOgrenci.email;
        txt_guvenlikSorusu.setText(seciliOgrenci.guvenlikSorusu+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_gSorusuCevap = new javax.swing.JLabel();
        lbl_guvenlikSorusu = new javax.swing.JLabel();
        txt_guvenlikSorusu = new javax.swing.JTextField();
        txt_gSorusuCevap = new javax.swing.JTextField();
        lbl_sifreYenileme = new javax.swing.JLabel();
        btn_devam = new javax.swing.JButton();
        btn_geri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));

        lbl_gSorusuCevap.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_gSorusuCevap.setText("Güvenlik Sorusu Cevap");

        lbl_guvenlikSorusu.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_guvenlikSorusu.setText("Güvenlik Sorunuz");

        lbl_sifreYenileme.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        lbl_sifreYenileme.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sifreYenileme.setText("Şifre Yenileme");

        btn_devam.setText("Devam");
        btn_devam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_devamActionPerformed(evt);
            }
        });

        btn_geri.setText("Geri");
        btn_geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_geriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(btn_geri, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_devam, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(425, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_guvenlikSorusu)
                        .addGap(89, 89, 89))
                    .addComponent(lbl_gSorusuCevap))
                .addGap(170, 170, 170)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_gSorusuCevap)
                    .addComponent(txt_guvenlikSorusu, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(325, 325, 325))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(733, 733, 733)
                .addComponent(lbl_sifreYenileme)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(296, Short.MAX_VALUE)
                .addComponent(lbl_sifreYenileme)
                .addGap(192, 192, 192)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_guvenlikSorusu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_gSorusuCevap, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_gSorusuCevap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_guvenlikSorusu)))
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_geri, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_devam, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(211, 211, 211))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_devamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_devamActionPerformed

        Ogrenci secilenOgrenci = OgrenciTakipDB.emailİleOgrenciBilgileriAlma(email);
        if (secilenOgrenci.gSorusuCevap.equals(txt_gSorusuCevap)) {
            oSifreYenileme frame = new oSifreYenileme(secilenOgrenci);
            frame.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Cevabınız yanlış lütfen tekrar deneyiniz.");
        }
    }//GEN-LAST:event_btn_devamActionPerformed

    private void btn_geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_geriActionPerformed
        // TODO add your handling code here:
        oSifremiUnuttum frame = new oSifremiUnuttum();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_geriActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_devam;
    private javax.swing.JButton btn_geri;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_gSorusuCevap;
    private javax.swing.JLabel lbl_guvenlikSorusu;
    private javax.swing.JLabel lbl_sifreYenileme;
    private javax.swing.JTextField txt_gSorusuCevap;
    private javax.swing.JTextField txt_guvenlikSorusu;
    // End of variables declaration//GEN-END:variables
}
